pipeline {

    agent any 
        
    stages {


            stage('Build Application') {
                steps {
                    sh 'mvn -f java-tomcat-sample/pom.xml clean package'
                }
                post {
                    success{
                        echo "Now Archiving the Artifacts......"
                        archiveArtifacts artifacts: '**/*.war'
                    }
                }
            }

            stage('Staging Deployment') {
                steps {
                    build job: 'Deploy App Staging Area'
                }
       
            }

             stage('Production Deployment'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy App Production'
            }
        }



    }


}
