pipeline {
    
    agent any

    stages {
    
        stage('Build Application') {
    
            steps {
                
                sh 'mvn -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true -f java-tomcat-sample/pom.xml clean package'

            }
    
            post {
    
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
    
        }

    }

}