pipeline {
    
    agent any

    stages {
    
        stage('Build Application') {
    
            steps {
                
                sh 'mvn install package'

            }
    
            post {
    
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
    
        }

    }

}